//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/", ConfigurationName="ServiceReference.ComarcasServentias")]
    public interface ComarcasServentias
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="retornarTodasComarcas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(retornoBase))]
        System.Threading.Tasks.Task<ServiceReference.retornarTodasComarcasResponse> retornarTodasComarcasAsync(ServiceReference.retornarTodasComarcas request);
        
        [System.ServiceModel.OperationContractAttribute(Action="retornarServentiasPorComarca", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(retornoBase))]
        System.Threading.Tasks.Task<ServiceReference.retornarServentiasPorComarcaResponse> retornarServentiasPorComarcaAsync(ServiceReference.retornarServentiasPorComarca request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/")]
    public partial class retornoComarcaWS : retornoBase
    {
        
        private comarcaWS[] listaComarcasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaComarcas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public comarcaWS[] listaComarcas
        {
            get
            {
                return this.listaComarcasField;
            }
            set
            {
                this.listaComarcasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/")]
    public partial class comarcaWS
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private int instanciaField;
        
        private bool instanciaFieldSpecified;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int instancia
        {
            get
            {
                return this.instanciaField;
            }
            set
            {
                this.instanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool instanciaSpecified
        {
            get
            {
                return this.instanciaFieldSpecified;
            }
            set
            {
                this.instanciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/")]
    public partial class serventiaWS
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private int codigoComarcaField;
        
        private bool codigoComarcaFieldSpecified;
        
        private int instanciaField;
        
        private bool instanciaFieldSpecified;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoComarca
        {
            get
            {
                return this.codigoComarcaField;
            }
            set
            {
                this.codigoComarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoComarcaSpecified
        {
            get
            {
                return this.codigoComarcaFieldSpecified;
            }
            set
            {
                this.codigoComarcaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int instancia
        {
            get
            {
                return this.instanciaField;
            }
            set
            {
                this.instanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool instanciaSpecified
        {
            get
            {
                return this.instanciaFieldSpecified;
            }
            set
            {
                this.instanciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(retornoServentiaWS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(retornoComarcaWS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/")]
    public abstract partial class retornoBase
    {
        
        private int codigoRetornoField;
        
        private bool codigoRetornoFieldSpecified;
        
        private string mensagemTecnicaField;
        
        private string mensagemUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoRetornoSpecified
        {
            get
            {
                return this.codigoRetornoFieldSpecified;
            }
            set
            {
                this.codigoRetornoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensagemTecnica
        {
            get
            {
                return this.mensagemTecnicaField;
            }
            set
            {
                this.mensagemTecnicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensagemUsuario
        {
            get
            {
                return this.mensagemUsuarioField;
            }
            set
            {
                this.mensagemUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/")]
    public partial class retornoServentiaWS : retornoBase
    {
        
        private serventiaWS[] listaServentiasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaServentias", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public serventiaWS[] listaServentias
        {
            get
            {
                return this.listaServentiasField;
            }
            set
            {
                this.listaServentiasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarTodasComarcas", WrapperNamespace="http://stubs.tribunal.djows.bb.com.br/", IsWrapped=true)]
    public partial class retornarTodasComarcas
    {
        
        public retornarTodasComarcas()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarTodasComarcasResponse", WrapperNamespace="http://stubs.tribunal.djows.bb.com.br/", IsWrapped=true)]
    public partial class retornarTodasComarcasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.retornoComarcaWS @return;
        
        public retornarTodasComarcasResponse()
        {
        }
        
        public retornarTodasComarcasResponse(ServiceReference.retornoComarcaWS @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarServentiasPorComarca", WrapperNamespace="http://stubs.tribunal.djows.bb.com.br/", IsWrapped=true)]
    public partial class retornarServentiasPorComarca
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoComarca;
        
        public retornarServentiasPorComarca()
        {
        }
        
        public retornarServentiasPorComarca(int codigoComarca)
        {
            this.codigoComarca = codigoComarca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarServentiasPorComarcaResponse", WrapperNamespace="http://stubs.tribunal.djows.bb.com.br/", IsWrapped=true)]
    public partial class retornarServentiasPorComarcaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stubs.tribunal.djows.bb.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference.retornoServentiaWS @return;
        
        public retornarServentiasPorComarcaResponse()
        {
        }
        
        public retornarServentiasPorComarcaResponse(ServiceReference.retornoServentiaWS @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ComarcasServentiasChannel : ServiceReference.ComarcasServentias, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ComarcasServentiasClient : System.ServiceModel.ClientBase<ServiceReference.ComarcasServentias>, ServiceReference.ComarcasServentias
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ComarcasServentiasClient() : 
                base(ComarcasServentiasClient.GetDefaultBinding(), ComarcasServentiasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ComarcasServentiasPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComarcasServentiasClient(EndpointConfiguration endpointConfiguration) : 
                base(ComarcasServentiasClient.GetBindingForEndpoint(endpointConfiguration), ComarcasServentiasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComarcasServentiasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ComarcasServentiasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComarcasServentiasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ComarcasServentiasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComarcasServentiasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.retornarTodasComarcasResponse> ServiceReference.ComarcasServentias.retornarTodasComarcasAsync(ServiceReference.retornarTodasComarcas request)
        {
            return base.Channel.retornarTodasComarcasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.retornarTodasComarcasResponse> retornarTodasComarcasAsync()
        {
            ServiceReference.retornarTodasComarcas inValue = new ServiceReference.retornarTodasComarcas();
            return ((ServiceReference.ComarcasServentias)(this)).retornarTodasComarcasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.retornarServentiasPorComarcaResponse> ServiceReference.ComarcasServentias.retornarServentiasPorComarcaAsync(ServiceReference.retornarServentiasPorComarca request)
        {
            return base.Channel.retornarServentiasPorComarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.retornarServentiasPorComarcaResponse> retornarServentiasPorComarcaAsync(int codigoComarca)
        {
            ServiceReference.retornarServentiasPorComarca inValue = new ServiceReference.retornarServentiasPorComarca();
            inValue.codigoComarca = codigoComarca;
            return ((ServiceReference.ComarcasServentias)(this)).retornarServentiasPorComarcaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ComarcasServentiasPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ComarcasServentiasPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8083/siscondjws_tjgo/comarcasServentiasService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ComarcasServentiasClient.GetBindingForEndpoint(EndpointConfiguration.ComarcasServentiasPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ComarcasServentiasClient.GetEndpointAddress(EndpointConfiguration.ComarcasServentiasPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ComarcasServentiasPort,
        }
    }
}
